### ISSUE TITLE
Cache data fails in case of local data (not S3)

### ISSUE THREAD

**Issue by afrittoli** [mtreinish/ciml#44]
Running
```
ciml-cache-data --build-name tempest-full --db-uri mysql+pymysql://query:query@logstash.openstack.org/subunit2sql
```

returns

```
Traceback (most recent call last):
  File "/git/github.com/mtreinish/ciml/.venv-mpl/bin/ciml-cache-data", line 10, in <module>
    sys.exit(cache_data())
  File "/System/Volumes/Data/git/github.com/mtreinish/ciml/.venv-mpl/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/System/Volumes/Data/git/github.com/mtreinish/ciml/.venv-mpl/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/System/Volumes/Data/git/github.com/mtreinish/ciml/.venv-mpl/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/System/Volumes/Data/git/github.com/mtreinish/ciml/.venv-mpl/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/git/github.com/mtreinish/ciml/ciml/gather_results.py", line 734, in cache_data
    s3_url)
  File "/git/github.com/mtreinish/ciml/ciml/gather_results.py", line 746, in cache_data_function
    runs, build_name, limit, '1s', db_uri, data_path=data_path, s3=s3)
  File "/git/github.com/mtreinish/ciml/ciml/gather_results.py", line 424, in gather_and_cache_results_for_runs
    data_path=data_path, s3=s3)
  File "/git/github.com/mtreinish/ciml/ciml/gather_results.py", line 335, in _get_data_for_run
    use_http=use_remote, data_path=data_path, s3=s3)
  File "/git/github.com/mtreinish/ciml/ciml/gather_results.py", line 171, in _get_dstat_file
    run_uuid, use_s3, s3)
TypeError: 'NoneType' object is not iterable
```

**Comment by afrittoli** [comment]
`_get_data_handlers` should always return a tuple
